### ISSUE TITLE
字幕下载中的英文字幕都是0字节

### ISSUE THREAD

**Issue by xin344** [FindHao/findyoutube.net#2]
望修复，谢谢。

**Comment by FindHao** [comment]
你得给个例子。。给个url。
另外，最好不要在github提issue，在博客留言我可以收到邮件回复。github的通知我一般不太看。

**Comment by FindHao** [comment]
在youtube视频页面确认那个视频有字幕先。如果连自动字幕都没有，当然下不到字幕。
